### ISSUE TITLE
Middle click to paste weirdness

### ISSUE THREAD

**Issue by keshto** [dabisu/sakura#12]
When selecting text from another application (firefox) and middle clicking in sakura, the last ctrl+c value is pasted instead. When middle clicking in any other program termit, firefox, etc the middle click pastes the previous selected text as expected.

**Comment by dabisu** [comment]
I already merged a patch for the clipboard problem, but there hasn't been a release yet. Please use github last version or wait for a 3.8.5 release, that should fix it.
