### ISSUE TITLE
Default windows size can not be controlled via configuration file

### ISSUE THREAD

**Issue by karypid** [dabisu/sakura#18]
Hello,

Currently, it is only possible to set the initial window size via the -c/--columns and -r/--rows` parameters. If you want a different-sized window you need to create a custom desktop launch file.

It would be nice to be able to set the defaults in the configuration file. Since it is quite easy to implement I have opened [PR17](https://github.com/dabisu/sakura/pull/17) for this.

Would appreciate it if you included this in mainline...

**Comment by dabisu** [comment]
Yes, you're right, it can be useful to be able to configure those values from the config file. I've already merged your patch. Thank you and sorry for the delay!
