### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by FromOopsToOps** [dabisu/sakura#2]
Hey David,

first of all, thanks for Sakura! It's been my only terminal emulator since September/20, works flawlesly!

I wanted to ask you if you plan on, or if it already does, support Wayland.
I might have to migrate to Wayland and am considering how to set it up so my workflow doesn't change.

I couldn't find any direct answer, nor could I find if libvte supports Wayland, or if you call to GTK 3.x (which I know supports Wayland).

Thanks in advance!

**Comment by dabisu** [comment]
Thanks! I'm glad that you like sakura.

Yes, it supports Wayland. Not directly, because anything related to Wayland support is the work of low level libraries like GTK 3.x.

Maybe there could be some issues that only affect Wayland (I remember there was a Wayland-related bug that was solved some time ago). But currently there are none that I know of. Please send a bug report if you find anything!

**Comment by FromOopsToOps** [comment]
Will do, man!
Really appreciate your effort!

I'll be testing it probably later today.

**Comment by FromOopsToOps** [comment]
Hey @dabisu !
I'm just testing out and there seems to be a bit of strange behavior that I'm not sure it's Sakuras fault.

I'm using Gentoo, latest stable kernel, latest stable sway, latest stable sakura.

Steps to reproduce:
1 - open sakura and set it to floating
2 - set up screen sizes with `swaymsg output eDP1 pos 0 0 res 1366x768` and `swaymsg output HDMI-A-1 pos 1366 0 res 1920x1080`
3 - set up wallpaper with `swaymsg output "*" bg "/home/odin/Imagens/Wallpapers/Desktop-FullHD/Sunset Valley.jpg" fill`.

Expected behavior: wallpaper is set on both screens, terminal is a black block.
Current behavior: wallpaper is set on both screens, terminal becomes translucid (dafuq)

4 - close terminal, open it again full screen.

Expected behavior: terminal would either load translucid, or black.
Current behavior: screen sizes and position are reset, wallpaper is reset to a grey backdrop.

Partly this behavior doesn't happen with i3-sensible-terminal (the only other terminal app I have). i3-sensible-terminal doesn't get translucent, only sakura does.

How can I go about debugging this?

Thanks in advance!

**Comment by FromOopsToOps** [comment]
Just to give more information:

tested a bunch, the transparency is related to the fact that I wasn't running a compositor before on i3wm/X11 and now on sway/Wayland the transparency setting does come into account.

The problem of resetting my screen resolution and wallpaper though continue, but it ain't only in Sakura. It happens on Gnome Terminal as well, so I think it's related to some library both application needs.

**Comment by dabisu** [comment]
Thanks for the report. Anyway next ime I'll test sakura with i3wm (never did it before) to see if I notice any problems.
