### ISSUE TITLE
Failure to paste selected text with '

### ISSUE THREAD

**Issue by lembark** [dabisu/sakura#20]
Pasting selected text into Sakura from other X11 windows does not use the select buffer.
I have "copy_on_select=true" set in the config, but I think that affects transfers the other way (i.e., from sakura -> xterm w/o using ^C).

What I need to do is copy content from a remote system which lacks sakura to a local system w/ sakura running. 

e.g., 

mrxvt -ls &
sakura &;

<select sakura>
ls;
<hillite a file & hit ^C>
<select mrxvt>
ls;
<hilite a selection of text in mrxvt>
<select sakura>
<middle-click == paste>

Result is the text selected via ^C w/in sakura, not the currently hilited text. 

Problem here is that it leaves users unable to paste into sakura from any X11 application that doesn't use ^C to populate the cut buffer (e.g., xterm, rxvt, mrxvt). 

Sakura is a nice enough program if I could just get it to paste the selected text. Without that it is useless for most of my work since I frequently have to cust+paste information between command line instances. 

Thanks

**Comment by jrouvier** [comment]
This is a bug that was fixed in 3.5.8. If you are running Ubuntu 22.04 you'll need to compile from source.
See https://bugs.launchpad.net/sakura/+bug/1948479

**Comment by dabisu** [comment]
Sorry for the delayed response. As jrouvier says please use 3.8.5. Anyway, I'll release a 3.8.6 with the latest bug fixes in git.
