### ISSUE TITLE
Cut+Paste on X11 does not work.

### ISSUE THREAD

**Issue by lembark** [dabisu/sakura#22]
Repeatable: Hightlight anything w/ left-click + drag; left click Sakura window; middle (i.e., 2nd button) click on X11 should paste but I don't get the highlighted text. 

Using ^C or ^X in some applications that support a separate cut buffer (vs. the highlight buffer) does work but this is > not< the X11 standard and leaves Sakura pretty much useless on with any standard X11 packages. Simple enough fix: If anything is highlighted in the current context then paste it.

**Comment by jrouvier** [comment]
This is a bug that was fixed in 3.5.8.  If you are running Ubuntu 22.04 you'll need to compile from source.
See https://bugs.launchpad.net/sakura/+bug/1948479

**Comment by dabisu** [comment]
Sorry for the delayed response. As jrouvier says please use 3.8.5. Anyway, I'll release a 3.8.6 with the latest bug fixes in git.

Thanks jrouvier for answering this.
