### ISSUE TITLE
problem with cursor_type=VTE_CURSOR_SHAPE_IBEAM

### ISSUE THREAD

**Issue by peter-joo** [dabisu/sakura#24]
The
cursor_type=VTE_CURSOR_SHAPE_BLOCK
works, but the
cursor_type=VTE_CURSOR_SHAPE_IBEAM
does not, but it should I suppose.

Reference:
https://developer-old.gnome.org/vte/unstable/VteTerminal.html

sakura version: 3.8.6
OS: Arch Linux

**Comment by dabisu** [comment]
I've just tested it and it works... so not sure what can be the reason of not showing in your system.
