### ISSUE TITLE
On Ubuntu 22.04 the icon in the gnome dock "dances" as if there is a notification in the window

### ISSUE THREAD

**Issue by mattip** [dabisu/sakura#27]
Thanks for sakura.
I am not sure if this is a sakura problem, a dbus problem, a gnome problem or something else. Any ideas why the icon "rocks" back and forth as if there is a notification?

![gnome docker](https://user-images.githubusercontent.com/823911/215396531-5d84e753-0e13-4325-b3c3-1a9a6d1a45ac.gif)

**Comment by mattip** [comment]
I did the latest ubuntu `apt update; apt upgrade` and yesterday the "dancing" stopped. I have no idea what caused the issue nor what solved it. Thanks again for sakura.

**Comment by dabisu** [comment]
I noticed this problem before, good to know that the latest update solves it. Thanks for the info!

**Comment by mattip** [comment]
I didn't want to drive the devs crazy here, but the problem has returned. I am not sure what triggers it, or even how to start debugging it.

**Comment by dabisu** [comment]
Don't worry about it. If  it still happensI think it's sakura's fault and it's related to the handling of urgent hint events... I'll look into it, but I don't know when ;)

**Comment by dabisu** [comment]
I found the bug that caused this problem, so it should be fixed in the last revision.

**Comment by mattip** [comment]
Thanks!
