### ISSUE TITLE
Bell/Beep

### ISSUE THREAD

**Issue by pr-asadi** [dabisu/sakura#32]
Greetings. How can I enable the beep/bell?
When I execute: `sleep 5 ; printf "\a"` and I change the workspace, it does not alert.
I use dwm, for example I open Sakura in workspace 1, and I execute that command, I immediately go to workspace 5, but the background of workspace 1 does not turn to white.
(urget_bell and audible_bell are set to `yes`)

**Comment by merore** [comment]
I have the opposite problem to yours. My taskbar is highlighted when a bell occurs in Sakura, but it cannot cancel this state even if i have focused on Sakura.

In fact I'm not sure it's Sakura's issue or GTK.  My environmens is  `Debian 10` and `Mate Desktop`.

![cc744aa0e93a0dfac558ea557176259](https://user-images.githubusercontent.com/77666634/233597056-69b73cfe-18e4-4172-9319-86cd57e23c0c.png)

**Comment by merore** [comment]
@dabisu

**Comment by dabisu** [comment]
@merore I did a small change and I think your problem should be solved.
@merore It should work if it's enabled in the menu. I don't have dwm installed so I haven't tested it yet. I see if I can install it and see what's happening. Does the urgent bell works with other terminals in dwm?

**Comment by pr-asadi** [comment]
@dabisu Yes it does work. When I use the `st` terminal it does alert/hilight the workspace background.
But not with Sakura.

**Comment by merore** [comment]
@dabisu Thanks, It works perfectly!

**Comment by dabisu** [comment]
@pr-asadi I just downloaded dwm and it works. I ran an 'sleep 5; printf "\a"' in a sakura terminal, changed to another workspace, and the workspace background where sakura is turned white.

**Comment by pr-asadi** [comment]
@dabisu Yes. I did rename my Sakura conf and it worked. Sorry to bother. Thank you for answering.

**Comment by pr-asadi** [comment]
We do not have a wiki for configuration? I could not find it in the repository.

**Comment by dabisu** [comment]
@pr-asadi Glad to hear that it works now! And no, there's no wiki.
