### ISSUE TITLE
-x | -e commands only apply to first tab

### ISSUE THREAD

**Issue by 0ion9** [dabisu/sakura#33]
Minimal example: `sakura --ntabs=2 -x 'seq 1 10'`.

Actual result: first tab runs the seq command. Remaining tabs run $SHELL (`/usr/bin/fish` in my case)

Expected result: All tabs initially created use the command specified by `-x`

Platform info: Sakura 3.8.7 on Arch Linux x86_64, XOrg 21.1.8, WM=spectrwm git 3.4.1.r46.gefc458e

My use case : `sakura --ntabs=$N -x "tmux $args"`. It *is* possible to have tabs which each run tmux by setting the `default-shell` option in tmux.conf and then running sakura with a SHELL override ie `SHELL=/usr/bin/tmux sakura --ntabs=$N`. However it's not possible to set the arguments to pass to tmux via SHELL.

**Comment by dabisu** [comment]
Sorry for the delayed response. I just commited a change that solves this issue. Thanks for your report.
