### ISSUE TITLE
no documentaion to create a new color palette

### ISSUE THREAD

**Issue by nakibrayan3** [dabisu/sakura#36]
i want to add dracula color scheme to the default color palettes but i don't what color is which (blue, yellow, green, etc...).

```c
const GdkRGBA dracula_palette[PALETTE_SIZE] = {
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1},
        {0, 0, 0, 1}
};
```

**Comment by dabisu** [comment]
Hello. Palette are in GdkRGBA format, you should get the rgba data for the Dracula palette. I see in dracula website are available in rgb, you just need to convert the values (0-254) to a (0-1) scale.

**Comment by nakibrayan3** [comment]
i get that. bit which one of the list items is red, blue, ...etc ?

**Comment by dabisu** [comment]
From the GTK documentation:

GdkRGBA is a convenient way to pass colors around. It’s based on cairo’s way to deal with colors and mirrors its behavior. All values are in the range from 0.0 to 1.0 inclusive. So the color (0.0, 0.0, 0.0, 0.0) represents transparent black and (1.0, 1.0, 1.0, 1.0) is opaque white. Other values will be clamped to this range when drawing.
