### ISSUE TITLE
Disabling Location/Command Display in Sakura Terminal (Title bar)

### ISSUE THREAD

**Issue by Jayanth-Parthsarathy** [dabisu/sakura#37]
Hello everyone! I recently installed Sakura and was thoroughly impressed with its capabilities, achieved through minimal lines of code. My appreciation goes out to the developer for their excellent work.

I've noticed that Sakura displays the current location or executing command in a bar at the top of the terminal, and I'm looking to disable this feature. According to the documentation, there's an option called "show_tab_bar," which I've attempted to set to both "false" and "never." Unfortunately, the bar remains visible. Could someone please assist me in resolving this issue?

Thank you!

**Comment by m-GDEV** [comment]
This works correctly for me, on Endeavours OS with the most updated version of sakura. 

Have you tried changing the option in the GUI?

You can do so like so: `Right Click -> Options -> Show Tab Bar`

**Comment by Jayanth-Parthsarathy** [comment]
Hello @m-GDEV, thank you for your response. I've set the 'show tab bar' option to 'never' in both the GUI and the config file for Sakura. I've also built Sakura from source, so I believe I'm using an updated version. However, the tab bar still appears when it shouldn't. Could you please provide guidance on how to resolve this issue?

![image](https://github.com/dabisu/sakura/assets/86654557/674ca20d-7193-4432-932f-17909dfac9f1)

**Comment by m-GDEV** [comment]
I also just built it from source and could not reproduce the issue. Could you post the output of the command `inxi -b` so I can see the system you're on?

**Comment by Jayanth-Parthsarathy** [comment]
Hey seems like the issue was with the windows manager I was using. Seems to work perfectly in dwl. Thanks for helping me out. I was using river wm with Artix linux.
