### ISSUE TITLE
Windows Key Accelerator No Longer Working

### ISSUE THREAD

**Issue by m-GDEV** [dabisu/sakura#38]
I'v been using sakura for some time now and I had the Windows key accelerator (aka: `64 | Gdk::MOD4_MASK`) to switch between tabs using the `switch_tab_accelerator` option in the config.

Its been working as expected for a few years but recently I noticed it no longer works for some reason. Instead of registering the special key press it just registers a letter. For example if I press: `WinKey + l` it used to move to the tab on the right. Now it just types `l`

 I can't confidently say it is a sakura issue but it seems like it. I'd appreciate help to determine the root cause. Thanks.

Here is my sakura.conf:
``
[sakura]
colorset1_fore=rgb(255,255,255)
colorset1_back=#1A1D45
colorset1_key=F1
colorset2_fore=rgb(192,192,192)
colorset2_back=rgb(0,0,0)
colorset2_key=F2
colorset3_fore=rgb(192,192,192)
colorset3_back=rgb(0,0,0)
colorset3_key=F3
colorset4_fore=rgb(192,192,192)
colorset4_back=rgb(0,0,0)
colorset4_key=F4
colorset5_fore=rgb(192,192,192)
colorset5_back=rgb(0,0,0)
colorset5_key=F5
colorset6_fore=rgb(192,192,192)
colorset6_back=rgb(0,0,0)
colorset6_key=F6
last_colorset=1
background=none
font=JetBrains Mono 11
show_always_first_tab=Yes
scrollbar=true
resize_grip=true
closebutton=true
tabs_on_bottom=false
less_questions=true
audible_bell=Yes
visible_bell=No
blinking_cursor=Yes
cursor_type=2
word_chars=-A-Za-z0-9,./?%&#_~
palette=1
add_tab_accelerator=5
del_tab_accelerator=5
switch_tab_accelerator=64
move_tab_accelerator=1
copy_accelerator=5
scrollbar_accelerator=5
open_url_accelerator=5
font_size_accelerator=4
set_tab_name_accelerator=5
add_tab_key=T
del_tab_key=W
prev_tab_key=h
next_tab_key=l
copy_key=C
paste_key=V
scrollbar_key=S
set_tab_name_key=N
fullscreen_key=F11
set_colorset_accelerator=5
icon_file=terminal-tango.svg
colorset1_curs=rgb(255,0,0)
colorset1_scheme=0
colorset2_curs=rgb(255,255,255)
colorset2_scheme=1
colorset3_curs=rgb(255,255,255)
colorset3_scheme=1
colorset4_curs=rgb(255,255,255)
colorset4_scheme=1
colorset5_curs=rgb(255,255,255)
colorset5_scheme=1
colorset6_curs=rgb(255,255,255)
colorset6_scheme=1
bold_is_bright=true
scroll_lines=10000
disable_numbered_tabswitch=false
use_fading=false
scrollable_tabs=true
urgent_bell=Yes
search_accelerator=5
search_key=F
increase_font_size_key=plus
decrease_font_size_key=minus
copy_on_select=false
paste_button=2
menu_button=3
show_tab_bar=multiple
window_columns=80
window_rows=24
```

**Comment by m-GDEV** [comment]
After some more research it seems like this issue was not present in commit `f65b4c632d37e461f17e5b64e65e315b460663a8`.

I had a feeling an update broke this functionality as it stopped working suddenly. 

I don't have time right now to determine which one but I'll look into it soon.

**Comment by dabisu** [comment]
Sorry for the delayed response. Got a fix for this, will commit it soon.
