### ISSUE TITLE
Disable Alt+L shortcut?

### ISSUE THREAD

**Issue by TheComet** [dabisu/sakura#44]
This is more a question than an issue, but whenever I press Alt+L, it will insert the ```ls``` command, and when I press Alt+H it will run help on the current command under my cursor.

While this is cool, it interferes with my tmux config... How can I turn off this behavior?

**Comment by dabisu** [comment]
Sakura doesn't insert any commands nor have any help feature. So i guess that is something configured in your shell or window manager.
