### ISSUE TITLE
Let programs catch mouse right click

### ISSUE THREAD

**Issue by T-3B** [dabisu/sakura#48]
Some programs like `nvim` allow the user to use the mouse right click to open some context menu.

Unfortunately, Sakura is the only one catching that event.

Right click in `nvim` in `xterm`:
![xterm](https://github.com/user-attachments/assets/777b3762-563c-4f01-a3d7-852d23623f88)
Right click in `nvim` in `sakura`:
![sakura](https://github.com/user-attachments/assets/ef41a322-b45f-4f49-8a42-fdfd207edb0d)

**Comment by dabisu** [comment]
This issue should be fixed with the last commit. Thanks for the report!

**Comment by T-3B** [comment]
Works perfectly, thank you! :)

**Comment by Zopiac** [comment]
What are the chances of allowing this to be configured by the user? As it stands, I cannot access Sakura's right click menu whatsoever when using `ncmpcpp` for instance.

**Comment by Zopiac** [comment]
Interesting! I know ncmpcpp uses left click but have no idea about right click. I suppose I simply assume that right clicking a terminal window will always pull up the right click menu, and so was taken aback when nothing happened in that program. I "resolved" my issue by rolling back to sakura 3.7.1  but it's good to know that the actual issue may lie elsewhere.
