### ISSUE TITLE
Allow configuring TERM

### ISSUE THREAD

**Issue by aragilar** [dabisu/sakura#49]
Currently `TERM` is hardcoded as `xterm-256color`. I don't think VTE supports all of the defined features of `xterm-256color`, so it would probably be better to move to `vte-256color` (though that should tested, and if there are slight differences a `sakura` entry should be created). As people may need to handle old terminfo databases on remote systems (though `vte-256color` has been around a while), adding an option to set `TERM` would be the simplest option.

**Comment by dabisu** [comment]
I've added an "term" option (only in the config file) to be able to change the default TERM value.
