### ISSUE TITLE
Wide characters overlap

### ISSUE THREAD

**Issue by T-3B** [dabisu/sakura#55]
This is the "three-em dash" unicode character ⸻ (U+2E3B).

Writing this in Sakura result in an overlap of several characters after it (three-em dash + 0 + 0; no space):
![image](https://github.com/user-attachments/assets/829f292f-d236-4178-904d-45c3ef6396f1)
While e.g. XTerm handles it correctly (it simply cuts the symbol):
![image](https://github.com/user-attachments/assets/abe95c0e-880c-4d0b-92c2-fbb72c7eaf25)

Same thing for "per ten thousand" unicode character ‱ (U+2031).
Sakura (per ten thousand + 0 + 0; no space):
![image](https://github.com/user-attachments/assets/cb8af058-3358-49d6-b057-80c32de8a205)
Xterm:
![image](https://github.com/user-attachments/assets/5884a23d-7128-4998-b465-916c6c7a12e7)

I have this problem with wide Japanese (or Chinese) chars too

**Comment by dabisu** [comment]
All the character drawing in sakura is done by the vte library (it uses gtk so pango...). I haven't looked if there is any current bug report about this wide character problem. Will let you know here if I find any info.

**Comment by T-3B** [comment]
Oh right, just tested and I have the same issue with another vte3-based terminal.

I just found several issues in the vte repository related to mine:
- https://gitlab.gnome.org/GNOME/vte/-/issues/2556 (this one is the shortest one to understand the cause of the problem)
- https://gitlab.gnome.org/GNOME/vte/-/issues/1975

I'll close this issue since it is not a problem from Sakura.
Thanks for your help and sorry for the disturbance.
