### ISSUE TITLE
Window title not showing current location

### ISSUE THREAD

**Issue by moranbw** [dabisu/sakura#56]
Hi there, enjoying the minimalism of the sakura terminal.  I however am having a small issue where the main window (and subsequent tabs) are not showing the current location.  It is just saying "sakura" or "Terminal 1", etc.

This is likely a product of my niche environment...Alpine Linux and the labwc compositor (v0.8.1).  If I can provide any debugging info for this issue let me know.  Or perhaps I am just missing a config option.

Thanks in advance!
![20241124_131708_grim](https://github.com/user-attachments/assets/eed76368-08c1-433c-8879-f439536b6b84)
![20241124_131733_grim](https://github.com/user-attachments/assets/c429725b-2b8e-4796-aa93-e30532af3bc6)

**Comment by moranbw** [comment]
I was able to manually get this working in my `.zshrc` with the following:
```
PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'
precmd() { eval "$PROMPT_COMMAND" }
```

**Comment by dabisu** [comment]
Hi, sorry for the delayed response. First time I heard of labwc (I'm too outdated about anything new😅) Glad you could fix it!
