### ISSUE TITLE
Not include / disable some features to decrease memory use.

### ISSUE THREAD

**Issue by ahmadraniri1994** [dabisu/sakura#8]
Hi, glad to use your terminal to work, is it possible to make sakura completely simple like xterm, no tab, etc ? I want to disable some features  to decrease memory use, as close as xterm does. Thank you.

**Comment by dabisu** [comment]
Hi, glad you like sakura. If there's only one tab, tab labels are disabled by default, so you can work just as if it's a terminal without tabs. Because it uses vte/gtk it'll never be as lightweight as xterm :(, anyway I don't plan to add new features and keep it as simple as possible.

**Comment by ahmadraniri1994** [comment]
Thanks, I get it. I'll close this. Once again thanks for the respond. :+1:
